### ISSUE TITLE
Questions about data processing

### ISSUE THREAD

**Issue by 12sun12** [zacharycbrown/ssl_baselines_for_biosignal_feature_extraction#4]
Thank you very much for your contribution. I am greatly inspired by it. About the content of the data set, I would like to ask, is this mouse data set public? Can you reveal the name of this data set? I need to work through this data set to extend to other data. So I have to take the liberty of disturbing you. Thank you very much for your help.

**Comment by zacharycbrown** [comment]
Hello! I'm glad you find the repository interesting!

I am glad you asked about the dataset - it is called the Tail Suspension Test (TST) dataset, and is a local field potential (LFP) dataset curated by Duke University's Collective for Psychiatric Neuroengineering (CPNE) - see their [webpage](https://www.collectiveneuro.com/) for further information on the lab. They have (fairly recently) granted us permission to share the dataset, but with some restrictions. I, for example, can not post the dataset publicly (e.g. on this public github repo), but I can share a .zip folder containing the non-public version upon individual request.

If you would like me to send you the dataset, please send me a private email at zac.brown@duke.edu so that I can share it with you. Please let me know if you have a preferred means of downloading the dataset (the unzipped version of the dataset I used is about 11.6 GB); otherwise, I believe I can find a way to share it with you via my duke.edu account(s).

Also, once you have the dataset, please let me know if you have additional questions as to its content/organization/structure/etc; since we've only recently been granted permission to share it, I recognize the documentation on this github repository may be insufficient for practical use.

**Comment by 12sun12** [comment]
Thanks for your help. I really need the Tail Suspension Test (TST) dataset, the dataset you mentioned, and would appreciate it if you could send it to me. If it's convenient, you can send it to [sunhua19982021@163.com](http://sunhua19982021@163.com/)  . Thank you, Sir.
